name:                sad

dependencies:
- base
- text
- megaparsec
- bytestring

default-extensions:
- OverloadedStrings

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Werror
- -Weverything
- -Wno-missing-kind-signatures
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-safe
- -Wno-missing-safe-haskell-mode
- -Wno-all-missed-specialisations
- -Wno-unsafe

executables:
  sad:
    main:                Main.hs
    source-dirs:         app
