name:                sad

dependencies:
- base

default-extensions:
- OverloadedStrings

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Werror
- -Weverything
- -Wno-missing-kind-signatures
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-safe
- -Wno-missing-safe-haskell-mode
- -Wno-all-missed-specialisations
- -Wno-type-defaults
- -Wno-unsafe
- -Wno-monomorphism-restriction
- -Wno-missing-deriving-strategies

executables:
  sad:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - text
    - megaparsec
    - bytestring
    - sad

library:
  source-dirs: src
  dependencies:
  - megaparsec
  - text

tests:
  sad-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - tasty
    - tasty-hunit
    - text
    - megaparsec
    - sad
